language: node_js
node_js: node
services:
- postgresql
before_script:
  - psql -c 'create database "test-simplify-app";' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: LcgrZUxpBPsipISNjTj/+QUeIWvgmCILqEEZn8G90b1vF8u1EuUk1WfM7HnNunfX9g7Pb6VwmGrLInZSxr+QW0DSJ1kKLXQvWFZ6jfTgMPJDOFSe6dpkyrNsl2BkmEZqR8n7xorTSPzbEosVjfGbyzf11kRvbWXeI7z3fnff8CryvIvi9oSvwZL1qO1vQjQrzVD3IRLfV8D++NccpdEwhxPXtTZZ36REcEkAk0KMw/uZXScNypTUBFwqJ6Te+YLO1LfAIyCPMiS0OQvRriyQ7q/7+g/KrTgajau9J/xMP6gHYEMOPV6Og+UxgJn/66CPP+3amk9Q5qW/ADvlybfWX0RJxNphBEV7+vCWFU4YSvvqcFzIxpuiL1lh/3zNQHdp4AEro8yDjZMln0jaJpou34nUGuf4k2ZeAb12lFsYzJ1S4DOfF5LjnC5p/FBiDh9S+1t6HgKHKkMTVLhJJfOL45qzMHJbnVu+folFYlAdgdkc2fBp7/s9CSwmlD0B1YFWZx3+Raj5nwhzCIoFrou8r7u/wRhnDh4GOhkTIznrTOMdgnEK+DqRhID72826CgRBiLZDgwwmxzZ+SbqOFFvsGQt23KPkPxz+N9R8/cFs2a8pzkRhCBrgFBbOMjvx7H0FyiSkkEXDZHsL4KRkq4gLnffuoLq6+82rCB9vQeb/qpM=
  app: whispering-ocean-59191
  on:
    repo: Jollendi91/simplify-budgeting-api
